version: '3.2'

services:
  database:
    image: mariadb:10.2
    working_dir: /srv
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/config:/etc/mysql/mysql.conf.d/:ro
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  php:
    build: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv
    ports:
      - "8001:8000"
volumes:
  database: ~
